 const desafios = {
      quente: [
        "Beije o parceiro(a) por 30 segundos sem usar as mãos.",
        "Sussurre algo excitante no ouvido dele(a).",
        "Dê uma mordidinha suave no lábio inferior dele(a).",
        "Dance no colo por uma música inteira.",
        "Lamba os dedos dele(a) lentamente.",
        "Faça uma massagem nos pés usando óleo.",
        "Dê um beijo de língua nos dedos dele(a).",
        "Faça um elogio safado com voz sexy.",
        "Faça um striptease.",
        "Beije o pescoço dele(a) devagar.",
        "Provoque com toques leves usando penas a ponta dos dedos.",
        "Escolha uma peça de roupa para ele(a) tirar.",
        "Dê beijos em 5 partes diferentes do corpo.",
        "Estimule o parceiro(a) apenas com toques leves por 1 minuto.",
        "Beije até chegar ao umbigo.",
        "Beije por trás, começando do pescoço até a lombar.",
        "Diga uma frase de filme adulto com sua voz mais sexy.",
        "Passe sua língua no lóbulo da orelha dele(a).",
        "Dê um tapa no bumbum dele(a).",
        "Lamba algo doce do corpo dele(a).",
        "Use uma venda e deixe ele(a) te beijar onde quiser por 30 segundos.",
        "Toque em si mesmo(a) de maneira sensual, olhando para ele(a).",
        "Morda levemente o ombro dele(a).",
        "Faça carinho na parte interna das coxas.",
        "Faça carinho com a boca sem beijar.",
        "Provoque passsando a língua pelo corpo do seu parceiro(a).",
        "Deslize seus dedos lentamente pelas costas.",
        "Dê um beijo apaixonado por 15s",
        "Tire uma peça de roupa do pareciro(a)"
      ],
      picante: [
        "Parceiro 1, no ouvido de parceiro 2 fale lentamente três frases que deixariam ele(a) maluco(a).",
        "Beije o corpo inteiro dele(a) sem usar as mãos.",
        "Morda lentamente a orelha do parceiro(a)",
        "Acaricie o pescoço do paceiro(a) por 30s olhando nos olhos",
        "Faça uma massagem sensual de 2 minutos com óleo ou creme.",
        "Tire uma peça de roupa lentamente enquanto ele(a) te observa.",
        "Beije entre as coxas sem tocar as partes íntimas.",
        "Use a boca para provocar por 1 minuto sem beijar.",
        "Simule sexo oral.",
        "Imite uma cena quente de filme por 30 segundos.",
        "Deixe o parceiro(a) te explorar com os olhos vendados.",
        "Descreva uma fantasia sua no ouvido dele(a), com detalhes.",
        "Provoque com um vibrador ou brinquedo",
        "Morda, lamba e beije o mamilo.",
        "Fique de quatro e peça para ele(a) te olhar por 15 segundos.",
        "Simule um gemido leve enquanto ele(a) toca você.",
        "Lamba o corpo dele(a) como se fosse um sorvete.",
        "Brinque com a língua onde preferir",
        "Lamba o pescoço e morda de leve.",
        "Faça barulhos sensuais no ouvido dele(a).",
        "Morda ou lamba os glúteos dele(a) por 10 segundos.",
        "Escolha um lugar do corpo e peça para ele(a) beijar lentamente.",
        "Beije até deixar arrepiado(a).",
        "Sente no colo e mova lentamente o quadril.",
        "Explore os pontos fracos do parceiro(a)"
      ],
      extremo: [
        "Faça sexo oral por 1 minuto.",
        "Permita que ele(a) te amarre por 3 minutos.",
        "Provoque com um brinquedo íntimo enquanto ele(a) assiste.",
        "Toque-se de verdade na frente dele(a) até quase gozar.",
        "Dê um tapa firme no bumbum dele(a) e morda depois.",
        "Realize uma posição sexual diferente da habitual.",
        "Fique nu(a) e desfile à vista dele(a).",
        "Faça um striptease com música sensual.",
        "Faça sexo oral com os olhos vendados.",
        "Deixe ele(a) escolher onde beijar por 1 minuto.",
        "Gema de forma intensa por 30 segundos.",
        "Deixe ele(a) te dominar (ou o contrário) por 2 minutos.",
        "Deixe que ele(a) use as mãos como quiser por 1 minutos.",
        "Deixe ele(a) te tocar enquanto você assiste.",
        "Faça amor em frente ao espelho",
        "Faça um oral com as mãos dele(a) amarradas.",
        "Provoque e impeça ele(a) de tocar por 2 minutos.",
        "Dê ordens ao parceiro(a) de forma sensual.",
        "Tire toda a roupa e fique de pé, esperando ele(a).",
        "Lamba as partes íntimas por 30 segundos.",
        "Faça um desafio de quem geme mais baixo durante carícias.",
        "Faça o parceiro(a) gozar só com palavras e toques.",
        "Escolha uma palavra proibida. Toda vez que disser ela, ganha um castigo...",
        "Amarre os braços do parceiro(a) e provoque como quiser, quem recebe é proibido reagir!",
        "Apenas obedeça",
        "Sente no seu parceiro(a) e não diga nada por 1 minuto. Só respire perto. Parceiro(a), pode tocar, mas não falar."
      ]
    };

    function mostrarDesafio() {
      const nivel = document.getElementById('nivel').value;
      const lista = desafios[nivel];
      const desafio = lista[Math.floor(Math.random() * lista.length)];
      document.getElementById('desafio').textContent = desafio;
    }

