 const desafios = {
      quente: [
        "Beije o parceiro(a) por 30 segundos sem usar as mãos.",
        "Sussurre algo excitante no ouvido dele(a).",
        "Dê uma mordidinha suave no lábio inferior dele(a).",
        "Dance no colo por uma música inteira.",
        "Lamba os dedos dele(a) lentamente.",
        "Faça uma massagem nos pés usando óleo.",
        "Passe gelo no corpo do parceiro(a) por 20 segundos.",
        "Dê um beijo de língua nos dedos dele(a).",
        "Faça um elogio safado com voz sexy.",
        "Simule um striptease (com roupas).",
        "Beije o pescoço dele(a) devagar.",
        "Provoque com toques leves usando penas ou a ponta do cabelo.",
        "Escolha uma peça de roupa para ele(a) tirar.",
        "Dê beijos em 5 partes diferentes do corpo.",
        "Estimule o parceiro(a) apenas com toques leves por 1 minuto.",
        "Beije até chegar ao umbigo.",
        "Beije por trás, começando do pescoço até a lombar.",
        "Diga uma frase de filme adulta com sua voz mais sexy.",
        "Passe sua língua no lóbulo da orelha dele(a).",
        "Dê um tapa leve no bumbum dele(a).",
        "Lamba algo doce do corpo dele(a).",
        "Use uma venda e deixe ele(a) te beijar onde quiser por 30 segundos.",
        "Toque em si mesmo(a) de maneira sensual, olhando para ele(a).",
        "Use os pés para provocar.",
        "Morda levemente o ombro dele(a).",
        "Faça carinho na parte interna das coxas.",
        "Passe um cubo de gelo no seu próprio corpo, olhando para ele(a).",
        "Faça carinho com a boca sem beijar.",
        "Simule um beijo molhado no ar, olhando para ele(a).",
        "Diga 'quero você agora' da forma mais provocante possível."
      ],
      picante: [
        "Beije o corpo inteiro dele(a) sem usar as mãos.",
        "Faça uma massagem sensual de 2 minutos com óleo ou creme.",
        "Tire uma peça de roupa lentamente enquanto ele(a) te observa.",
        "Beije entre as coxas sem tocar as partes íntimas.",
        "Use a boca para provocar por 1 minuto sem beijar.",
        "Simule sexo oral (sem contato real).",
        "Imite uma cena quente de filme por 30 segundos.",
        "Deixe o parceiro(a) te explorar com os olhos vendados.",
        "Descreva uma fantasia sua no ouvido dele(a), com detalhes.",
        "Provoque com um vibrador ou brinquedo, sem penetrar.",
        "Morda, lamba e beije o mamilo (ou simule).",
        "Use as mãos para simular uma transa sem roupa.",
        "Fique de quatro e peça para ele(a) te olhar por 15 segundos.",
        "Simule um gemido leve enquanto ele(a) toca você.",
        "Lamba o corpo dele(a) como se fosse um sorvete.",
        "Brinque com a língua no umbigo ou parte íntima coberta.",
        "Simule uma posição sexual, com roupas.",
        "Chupe um dedo dele(a) de forma provocante.",
        "Diga uma frase suja sem rir.",
        "Diga onde você quer ser tocado(a) agora.",
        "Toque suas partes íntimas por cima da roupa, olhando para ele(a).",
        "Lamba o pescoço e morda de leve.",
        "Simule que está se tocando e narre como se fosse real.",
        "Faça barulhos sensuais no ouvido dele(a).",
        "Morda ou lamba os glúteos dele(a) por 10 segundos.",
        "Escolha um lugar do corpo e peça para ele(a) beijar lentamente.",
        "Use o corpo para provocar (roçando, sentando, rolar juntos).",
        "Coloque os dois corpos bem colados e apenas respirem juntos.",
        "Passe um brinquedo íntimo no corpo dele(a) sem usar as mãos.",
        "Diga 'me usa' ou 'me domina' com voz firme e olho no olho."
      ],
      extremo: [
        "Faça sexo oral por 1 minuto (ou simule com contato).",
        "Permita que ele(a) te amarre por 3 minutos.",
        "Provoque com um brinquedo íntimo enquanto ele(a) assiste.",
        "Toque-se de verdade na frente dele(a) até quase gozar.",
        "Dê um tapa firme no bumbum dele(a) e morda depois.",
        "Realize uma posição sexual diferente da habitual.",
        "Fique nu(a) e ande lentamente à vista dele(a).",
        "Faça um striptease sem censura e com música sensual.",
        "Simule um roleplay (professor(a)/aluno(a), médico(a), etc.).",
        "Faça sexo oral com os olhos vendados.",
        "Deixe ele(a) escolher onde beijar por 1 minuto inteiro.",
        "Gema de forma intensa por 30 segundos.",
        "Deixe ele(a) te dominar (ou o contrário) por 5 minutos.",
        "Provoque usando apenas calcinha/cueca.",
        "Escreva algo com a língua no corpo dele(a).",
        "Use um objeto da casa como brinquedo erótico.",
        "Deixe que ele(a) use as mãos como quiser por 2 minutos.",
        "Descreva como foi a melhor transa entre vocês dois.",
        "Deixe ele(a) te tocar enquanto você assiste.",
        "Simule penetração com as roupas por 1 minuto.",
        "Faça amor em frente ao espelho (ou simule).",
        "Grite o nome dele(a) de forma intensa.",
        "Faça um oral com as mãos amarradas.",
        "Provoque e impeça ele(a) de tocar por 2 minutos.",
        "Imite a sua posição favorita em câmera lenta.",
        "Dê ordens ao parceiro(a) de forma sensual.",
        "Tire toda a roupa e fique de pé, esperando ele(a).",
        "Lamba as partes íntimas (real ou simulado) por 30 segundos.",
        "Faça um desafio de quem geme mais baixo durante carícias.",
        "Faça o parceiro(a) gozar só com palavras e toques leves."
      ]
    };

    function mostrarDesafio() {
      const nivel = document.getElementById('nivel').value;
      const lista = desafios[nivel];
      const desafio = lista[Math.floor(Math.random() * lista.length)];
      document.getElementById('desafio').textContent = desafio;
    }